apiVersion: v1
kind: Namespace
metadata:
  name: manifiesto01
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: manifiesto01
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: manifiesto01
spec:
  project: manifiesto01
# REPOSITORIO y PATHS
  source:
    repoURL: https://github.com/MrBorderline/argocd.git
    targetRevision: main
    path: official/examples/helm-guestbook
    helm:
      valueFiles:
        - values-test.yaml
# DESTINO DE CLUSTERS
  destination:
    server: https://kubernetes.default.svc
    namespace: manifiesto01
# SYNC POLICIES 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true

  ignoreDifferences:
    - group: "*"
      kind: "*"