apiVersion: v1
kind: Namespace
metadata:
  name: manifiesto02
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: manifiesto02
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: manifiesto02
spec:
  project: manifiesto02
# REPOSITORIO y PATHS
  source:
    repoURL: https://github.com/MrBorderline/argocd.git
    targetRevision: main
    path: official/examples/hello-world
    # helm:
    #   valueFiles:
    #     - values-test.yaml
# DESTINO DE CLUSTERS
  destination:
    server: https://kubernetes.default.svc
    namespace: manifiesto02
# SYNC POLICIES 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true

  ignoreDifferences:
    - group: "*"
      kind: "*"