apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: manifiesto02
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: manifiesto 01 project helloworld
  sourceRepos:
    #- '*'
    - https://github.com/MrBorderline/argocd.git

  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
      name: in-cluster

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'